/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/travel-history/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trips per destination planet, most travelled first. */
        get: operations["GetTravelStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/travel-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check the status of one call. */
        get: operations["GetTravelRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/travel-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paged log of every call that completed or was rejected. */
        get: operations["GetTravelHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the known planets and their space docks, nearest first. */
        get: operations["GetPlanets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shuttles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live state of every shuttle: location, trip, manifest and spare capacity. */
        get: operations["GetFleet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/travel-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Call a shuttle from a space dock to another planet. */
        post: operations["CallShuttle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CallShuttleLifeForm: {
            species: string;
            /** Format: double */
            weightKg: number;
        };
        CallShuttleRequest: {
            /** Format: int32 */
            originPlanetId: number;
            /** Format: int32 */
            destinationPlanetId: number;
            lifeForms: components["schemas"]["CallShuttleLifeForm"][];
        };
        CallShuttleResponse: {
            /** Format: int32 */
            travelRequestId: number;
            status: string;
            outcome: string;
            /** Format: int32 */
            lifeFormCount: number;
            /** Format: double */
            totalWeightKg: number;
            /** Format: int32 */
            shuttleId?: null | number;
            shuttleName?: null | string;
            /** Format: int32 */
            queuePosition?: null | number;
            rejectionReason?: null | string;
        };
        HealthResponse: {
            status: string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        LifeFormResponse: {
            species: string;
            /** Format: double */
            weightKg: number;
        };
        ManifestEntryResponse: {
            /** Format: int32 */
            travelRequestId: number;
            status: string;
            /** Format: int32 */
            lifeFormCount: number;
            /** Format: double */
            totalWeightKg: number;
        };
        PlanetResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            /** Format: int32 */
            distanceRank: number;
        };
        PlanetTravelStatsResponse: {
            /** Format: int32 */
            planetId: number;
            planet: string;
            /** Format: int32 */
            distanceRank: number;
            /** Format: int32 */
            completedTrips: number;
            /** Format: int32 */
            rejectedCalls: number;
            /** Format: int32 */
            lifeFormsDelivered: number;
            /** Format: double */
            weightDeliveredKg: number;
        };
        ShuttleResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            state: string;
            currentPlanet: null | string;
            flyingToPlanet: null | string;
            tripDestination: null | string;
            /** Format: date-time */
            arrivesAtUtc: null | string;
            /** Format: double */
            secondsUntilArrival: null | number;
            /** Format: int32 */
            lifeFormsAboard: number;
            /** Format: double */
            weightAboardKg: number;
            /** Format: int32 */
            remainingLifeForms: number;
            /** Format: double */
            remainingWeightKg: number;
            manifest: components["schemas"]["ManifestEntryResponse"][];
        };
        TravelHistoryItemResponse: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            travelRequestId: number;
            origin: string;
            destination: string;
            /** Format: int32 */
            lifeFormCount: number;
            /** Format: double */
            totalWeightKg: number;
            outcome: string;
            /** Format: int32 */
            shuttleId: null | number;
            /** Format: date-time */
            requestedAtUtc: string;
            /** Format: date-time */
            recordedAtUtc: string;
            rejectionReason: null | string;
        };
        TravelHistoryPageResponse: {
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            items: components["schemas"]["TravelHistoryItemResponse"][];
        };
        TravelRequestResponse: {
            /** Format: int32 */
            id: number;
            status: string;
            origin: string;
            destination: string;
            /** Format: int32 */
            lifeFormCount: number;
            /** Format: double */
            totalWeightKg: number;
            lifeForms: components["schemas"]["LifeFormResponse"][];
            /** Format: date-time */
            requestedAtUtc: string;
            /** Format: date-time */
            completedAtUtc: null | string;
            /** Format: int32 */
            shuttleId?: null | number;
            shuttleName?: null | string;
            /** Format: date-time */
            estimatedArrivalUtc?: null | string;
            /** Format: double */
            secondsUntilArrival?: null | number;
            rejectionReason?: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    GetTravelStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanetTravelStatsResponse"][];
                };
            };
        };
    };
    GetTravelRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TravelRequestResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetTravelHistory: {
        parameters: {
            query?: {
                Page?: number;
                PageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TravelHistoryPageResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetPlanets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanetResponse"][];
                };
            };
        };
    };
    GetFleet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShuttleResponse"][];
                };
            };
        };
    };
    CallShuttle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallShuttleRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallShuttleResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
}
