// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceTravel.Api.Data;

#nullable disable

namespace SpaceTravel.Api.Data.Migrations
{
    [DbContext(typeof(SpaceTravelDbContext))]
    [Migration("20260909010053_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SpaceTravel.Api.Domain.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistanceRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DistanceRank")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Planets", (string)null);
                });

            modelBuilder.Entity("SpaceTravel.Api.Domain.Shuttle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArrivesAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentPlanetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DepartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlyingToPlanetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlannedDestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPlanetId");

                    b.HasIndex("FlyingToPlanetId");

                    b.HasIndex("PlannedDestinationId");

                    b.ToTable("Shuttles", (string)null);
                });

            modelBuilder.Entity("SpaceTravel.Api.Domain.TravelHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinationPlanetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LifeFormCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginPlanetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShuttleId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalWeightKg")
                        .HasColumnType("REAL");

                    b.Property<int>("TravelRequestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DestinationPlanetId");

                    b.HasIndex("OriginPlanetId");

                    b.HasIndex("RecordedAtUtc");

                    b.HasIndex("TravelRequestId")
                        .IsUnique();

                    b.ToTable("TravelHistory", (string)null);
                });

            modelBuilder.Entity("SpaceTravel.Api.Domain.TravelRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedShuttleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationPlanetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginPlanetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedShuttleId");

                    b.HasIndex("DestinationPlanetId");

                    b.HasIndex("OriginPlanetId");

                    b.HasIndex("Status");

                    b.ToTable("TravelRequests", (string)null);
                });

            modelBuilder.Entity("SpaceTravel.Api.Domain.Shuttle", b =>
                {
                    b.HasOne("SpaceTravel.Api.Domain.Planet", null)
                        .WithMany()
                        .HasForeignKey("CurrentPlanetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SpaceTravel.Api.Domain.Planet", null)
                        .WithMany()
                        .HasForeignKey("FlyingToPlanetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SpaceTravel.Api.Domain.Planet", null)
                        .WithMany()
                        .HasForeignKey("PlannedDestinationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("SpaceTravel.Api.Domain.Capacity", "Capacity", b1 =>
                        {
                            b1.Property<int>("ShuttleId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaxLifeForms")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxLifeForms");

                            b1.Property<double>("MaxWeightKg")
                                .HasColumnType("REAL")
                                .HasColumnName("MaxWeightKg");

                            b1.HasKey("ShuttleId");

                            b1.ToTable("Shuttles");

                            b1.WithOwner()
                                .HasForeignKey("ShuttleId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceTravel.Api.Domain.TravelHistoryEntry", b =>
                {
                    b.HasOne("SpaceTravel.Api.Domain.Planet", null)
                        .WithMany()
                        .HasForeignKey("DestinationPlanetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpaceTravel.Api.Domain.Planet", null)
                        .WithMany()
                        .HasForeignKey("OriginPlanetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceTravel.Api.Domain.TravelRequest", b =>
                {
                    b.HasOne("SpaceTravel.Api.Domain.Shuttle", null)
                        .WithMany()
                        .HasForeignKey("AssignedShuttleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SpaceTravel.Api.Domain.Planet", null)
                        .WithMany()
                        .HasForeignKey("DestinationPlanetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpaceTravel.Api.Domain.Planet", null)
                        .WithMany()
                        .HasForeignKey("OriginPlanetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("SpaceTravel.Api.Domain.LifeForm", "LifeForms", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Species")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<int>("TravelRequestId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("WeightKg")
                                .HasColumnType("REAL");

                            b1.HasKey("Id");

                            b1.HasIndex("TravelRequestId");

                            b1.ToTable("LifeForms", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TravelRequestId");
                        });

                    b.Navigation("LifeForms");
                });
#pragma warning restore 612, 618
        }
    }
}
